ezresume2/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.http import HttpResponse
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from users import views as user_views
from . import views
from .sitemap import StaticSitemap

sitemaps = {'pages': StaticSitemap}

urlpatterns = [
    path('app/', include(('resumes.urls', 'resumes'), namespace='resumes')),
    path('accounts/', include('allauth.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('', views.home_view, name='home'),
    path('activate/<uidb64>/<token>/', user_views.activate, name='activate'),
    path('payment-notification/', user_views.payment_notification, name='payment-notif'),
    path('privacy/', views.privacy, name='privacy'),
    path('payment-confirmed/', user_views.payment_confirmed, name='payment-confirmed'),
    path('payment-unfinished/', user_views.payment_unfinished, name='payment-unfinished'),
    path('payment-error/', user_views.payment_error, name='payment-error'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    re_path(r'^robots\.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: ", mimetype="text/plain")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

resumes/urls.py
from django.urls import path

from . import views
from users import views as user_views

urlpatterns = [
    path('', views.my_resumes, name='my-resumes'),
    path('edit-profile/', views.edit_profile, name='edit-profile'),
    path('delete/<int:pk>/', views.delete_resume, name='delete-resume'),
    path('resume/create/', views.ResumeWizard.as_view(views.FORMS), name='create-resume'),
    path('edit/resume/<int:pk>/', views.ResumeWizard.as_view(views.FORMS), name='edit-resume'),
    path('faq/', views.faq, name='faq'),
    path('templates/', views.templates, name='templates'),
    path('payment/', user_views.payment, name='payment'),
    path('payment/notification/', user_views.payment_notification, name='payment-notif'),
    path('resume/<int:pk>/choose/', views.choose, name='choose'),
    path('resume/<int:pk>/view-resume/', views.choose, name='view-resume'),
]

users/models.py
from django_countries.fields import CountryField
from django.db import models
from django.contrib.auth.models import AbstractUser
from tinymce.models import HTMLField
from django_resized import ResizedImageField


class User(AbstractUser):
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.email


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    job_title = models.CharField(max_length=255, blank=True)
    phone_number = models.CharField(max_length=255, blank=True)
    address = models.CharField(max_length=255, blank=True)
    address2 = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=255, blank=True)
    country = CountryField(blank_label='(Select country)', blank=True)
    linked_in = models.CharField(max_length=255, blank=True)
    objective = HTMLField(blank=True)
    profile_pic = ResizedImageField(size=[300, 300], quality=100, default="profile-pics/default.jpg", upload_to="profile-pics")
    sub_expires_on = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.user.email


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    package = models.CharField(max_length=255)
    total = models.IntegerField()
    paid_status = models.BooleanField(default=False)

    def __str__(self):
        return self.package

users/forms.py
from django import forms
from django.forms import TextInput
from django.contrib.auth.forms import UserCreationForm
from .models import User
from django.contrib.auth.password_validation import validate_password


class CustomUserCreationForm(UserCreationForm):
    def clean_username(self):
        username = self.cleaned_data['username']
        if len(username) < 8:
            raise forms.ValidationError("Your username is too short. A username must be at least 8 characters long")
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("Your username is already taken")
        return username

    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if validate_password(password1):
            raise forms.ValidationError('This password is not valid')
        return password1

    def clean(self, *args, **kwargs):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")

        if password1 != password2:
            raise forms.ValidationError("Your passwords do not match. Please try again")
        return super(UserCreationForm, self).clean(*args, **kwargs)

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'email', 'password1', 'password2',)


class CustomUserChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', )
        widgets = {'first_name': TextInput(attrs={'placeholder': 'What is your first name?'}),
                   'last_name': TextInput(attrs={'placeholder': 'What is your last name?'}), }


class OrderForm(forms.Form):
    pass

users/views.py
import datetime
import json
import requests
import hashlib

from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.contrib import messages
from django.core.mail import EmailMessage
from django.contrib.auth.models import Group
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone

from .tokens import account_activation_token
from .forms import CustomUserCreationForm, OrderForm
from .models import Order, User


def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your EZResume account'
            message = render_to_string('users/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token': account_activation_token.make_token(user), })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()
            messages.success(request,
                             "Verification email sent to {}. Please activate your account ".format(user.email))
            return redirect('login')
    else:
        form = CustomUserCreationForm()
    return render(request, 'users/register.html', {'form': form})


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, "You're account is now active! Please login with your credentials")
        return redirect('login')
    else:
        return HttpResponse('Activation link is invalid!')


@csrf_exempt
def payment_notification(request):
    if request.method == "POST":
        body_unicode = request.body.decode('utf-8')
        request_dict = json.loads(body_unicode)
        order_id = request_dict['order_id']
        status_code = request_dict['status_code']
        gross_amount = request_dict['gross_amount']
        serverkey = 'Mid-server-2pj2krTSNlIM7PXH2PD-qxoC'

        if (request_dict["transaction_status"] == "settlement" or request_dict["transaction_status"] == "capture") and request_dict["status_code"] == "200":
            signature_key_encoded = (order_id + status_code + gross_amount + serverkey).encode('utf-8')
            m = hashlib.sha512()
            m.update(signature_key_encoded)

            if m.hexdigest() == request_dict['signature_key']:
                order = Order.objects.get(pk=order_id)
                user = order.user
                if order.package == '7 day':
                    user.profile.sub_expires_on = timezone.now() + datetime.timedelta(days=7)
                elif order.package == '1 month':
                    user.profile.sub_expires_on = timezone.now() + datetime.timedelta(days=30)
                user.save()
                order.paid_status = True
                order.save()
                group = Group.objects.get(name='paying_user')
                group.user_set.add(user)
                return HttpResponse(status=200)
            else:
                return HttpResponse(status=401)
        else:
            return HttpResponse(status=201)
    return redirect('home')


def payment_confirmed(request):
    messages.success(request, "Thank you for your purchase! You now have unlimited PDF exports!")
    return redirect('resumes:my-resumes')


def payment_unfinished(request):
    messages.info(request, "Your payment has not been completed. Please check your email and follow the instructions to complete your payment")
    return redirect('resumes:my-resumes')


def payment_error(request):
    messages.error(request, "There was an error processing your payment! Please try again...")
    return redirect('resumes:my-resumes')


def payment(request):
    user = request.user
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            # TODO: Change to production
            url = 'https://app.midtrans.com/snap/v1/transactions'
            if '7-day' in request.POST:
                order = Order.objects.create(user=user, package='7 day', total=24000)
            elif '1-month' in request.POST:
                order = Order.objects.create(user=user, package='1 month', total=72000)

            order_id = str(order.id)
            order_total = order.total

            headers = {
                'Accept': 'application/json',
                'Content-Type': 'application/json',
            }

            payload = {
                "transaction_details": {
                    "order_id": order_id,
                    "gross_amount": order_total
                },
                "item_details": {
                    "name": '{} package'.format(order.package),
                    "price": order.total,
                    "quantity": 1,
                },
                "customer_details": {
                    "first_name": user.first_name,
                    "last_name": user.last_name,
                    "email": user.email,
                },
                "billing_address": {
                    "first_name": user.first_name,
                    "last_name": user.last_name,
                    "email": user.email,
                },
            }

            snap_token = requests.post(url, auth=('Mid-server-2pj2krTSNlIM7PXH2PD-qxoC', ''),
                                       headers=headers, json=payload)
            response_dict = snap_token.json()
            redirect_url = response_dict['redirect_url']
            return redirect(redirect_url)
    else:
        form = OrderForm()
    return render(request, 'users/payment.html', {'form': form, 'user': user})

users/templates/users/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to complete your EZResume registration:

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}

With appreciation,



The EZResume Team
www.ezresume.id
{% endautoescape %}

users/templates/users/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>ERROR</h1>
</body>
</html>

users/templates/users/finish.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>FINISH</h1>
</body>
</html>

users/templates/users/login.html
{% load static %}
{% load socialaccount %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>EZResume | Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'users/images/icons/favicon.ico' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'users/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'users/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'users/fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'users/vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'users/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'users/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'users/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'users/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'users/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'users/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>

{% if messages %}
    <div class="messages">
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }} message-text"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

    <div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55">
                <div class="social-buttons">
                    <p class="login-with">
                        Login with
                    </p>
                    <p>
                        <a href="{% provider_login_url 'google' %}">
                            <img src="{% static 'images/btn_google_signin_dark_normal_web.png' %}"></a>
                        <a href="{% provider_login_url 'linkedin' %}" class="linkedin-button">
                            <i class="fa fa-linkedin fa-fw"></i> LinkedIn</a>
                    </p>
                </div>
				<form class="login100-form validate-form flex-sb flex-w" method="POST"
                      action="{% url 'login' %}">{% csrf_token %}
                    <span>
                        <h1>EZResume</h1>
					</span>
					<span class="login100-form-title p-b-32">
                        Account Login
					</span>

					<span class="txt1 p-b-11">
						Username
					</span>
					<div class="wrap-input100 validate-input m-b-36" data-validate = "Username is required">
						<input class="input100" type="text" name="{{ form.username.html_name }}">
						<span class="focus-input100"></span>
					</div>

					<span class="txt1 p-b-11">
						Password
					</span>
					<div class="wrap-input100 validate-input m-b-12" data-validate = "Password is required">
						<span class="btn-show-pass">
							<i class="fa fa-eye"></i>
						</span>
						<input class="input100" type="password" name="{{ form.password.html_name }}" >
						<span class="focus-input100"></span>
					</div>

                    <div class="flex-sb-m w-full p-b-48">
                        <!-- Remember me functionality is not used yet
						<div class="contact100-form-checkbox">
							<input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
							<label class="label-checkbox100" for="ckb1">
								Remember me
							</label>
						</div>
                        -->
						<div>
							<a href="{% url 'password_reset' %}" class="txt3">Forgot your password?</a>
						</div>
					</div>

<!----------------- Errors are displayed here --------------->
                    <div class="error-box">
                    {% if form.non_field_errors %}
                        <ul class='error-text'>
                            {% for error in form.non_field_errors %}
                                <li class="non-field-error">{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    </div>
<!----------------- End of errors display --------------->

                    <div class="container-login100-form-btn">
                        <button class="login100-form-btn" type="submit">Login</button>
					</div>

				</form>
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script src="{% static 'users/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'users/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'users/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'users/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'users/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'users/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'users/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'users/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'users/js/main.js' %}"></script>

</body>
</html>

users/templates/users/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logged Out</title>
</head>
<body>
<h2>You have been logged out</h2>
<p><a href="{% url 'login' %}">Login again</a></p>
<p><a href="{% url 'home' %}">Home</a></p>
</body>
</html>

users/templates/users/password_reset.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>EZResume | Reset Your Password</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'users/images/icons/favicon.ico' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'users/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'users/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'users/fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'users/vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'users/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'users/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'users/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'users/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'users/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'users/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55">
                <span class="login100-form-title p-b-32">
                    Reset your password
                </span>
                <span class="txt1 p-b-11">
                    Email Address
                </span>
				<form class="login100-form validate-form flex-sb flex-w" action="{% url 'password_reset' %}" method="POST">
                    {% csrf_token %}
                    <div class="wrap-input100 validate-input m-b-36" data-validate = "Email address is required">
						<input class="input100" type="text" name="email">
                        <span class="focus-input100"></span>
					</div>
                      <button class="login100-form-btn" type="submit">Request Email</button>
				</form>
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script src="{% static 'users/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'users/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'users/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'users/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'users/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'users/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'users/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'users/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'users/js/main.js' %}"></script>

</body>
</html>

users/templates/users/password_reset_complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>EZResume | Password Reset Complete</title>
</head>
<body>
<h2>Your password has been reset successfully</h2>
<p><a href="{% url 'login' %}">Login</a></p>
</body>
</html>

users/templates/users/password_reset_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Password Reset</title>
</head>
<body>
<h2>An email has been sent with instructions on how to reset your password</h2>
<p><a href="{% url 'home' %}">Home</a></p>
</body>
</html>

users/templates/users/payment.html
{% extends 'resumes/layout.html' %}
{% load staticfiles %}
{% block title %}<title>EZResume | Buy a Package</title>{% endblock %}
{% block subheader %}
    <div class="sub-header">
            {% if user.profile.sub_expires_on %}
                <h1 class="package-title">Your package expires on {{ user.profile.sub_expires_on|date:"D d M Y" }} at 23:59</h1>
            {% else %}
                <h1>You currently don't have a package</h1>
            {% endif %}
        <h1>Buy or Renew a Package</h1>
    </div>
{% endblock %}
{% block content %}
    <div class="form-labels-on-top payment-page">
        <div class="col-six plan-wrap">
            <div class="plan-block primary">
                <div class="plan-top-part">
                    <img src="{% static 'images/espresso-short.png' %}" id="short-photo" alt="espresso">
                    <h3 class="plan-block-title">7 Day Package</h3>
                    <p class="plan-block-price"><sup>IDR</sup>24,000</p>
                    <!--
                    <p class="plan-block-per">Per Month</p>
                    -->
                </div>
                <div class="plan-bottom-part">
                    <ul class="plan-block-features">
                        <li><span>Unlimited</span> PDF Exports</li>
                        <li><span>Access</span> To All Templates</li>
                        <li><span>One Time</span> Payment</li>
                    </ul>
                    <form method="post" action="{% url 'resumes:payment' %}">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" name="7-day">BUY NOW</button>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-six plan-wrap">
            <div class="plan-block primary">
                <div class="plan-top-part">
                    <div class="recommended">
                    </div>
                    <img src="{% static 'images/coffee-long.png' %}" id="long-photo" alt="long-black">
                    <h3 class="plan-block-title">1 Month Package</h3>
                    <p class="plan-block-price"><sup>IDR</sup>72,000</p>
                    <!--
                    <p class="plan-block-per">Per Month</p>
                    -->
                </div>
                <div class="plan-bottom-part">
                    <ul class="plan-block-features">
                        <li><span>Unlimited</span> PDF Exports</li>
                        <li><span>Access</span> To All Templates</li>
                        <li><span>One Time</span> Payment</li>
                    </ul>
                    <form method="post" action="{% url 'resumes:payment' %}">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" name="1-month">BUY NOW</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/unfinish.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>UNFINISH</h1>
</body>
</html>