ezresume2/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.http import HttpResponse
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from users import views as user_views
from . import views
from .sitemap import StaticSitemap

sitemaps = {'pages': StaticSitemap}

urlpatterns = [
    path('app/', include(('resumes.urls', 'resumes'), namespace='resumes')),
    path('accounts/', include('allauth.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('', views.home_view, name='home'),
    path('activate/<uidb64>/<token>/', user_views.activate, name='activate'),
    path('payment-notification/', user_views.payment_notification, name='payment-notif'),
    path('privacy/', views.privacy, name='privacy'),
    path('payment-confirmed/', user_views.payment_confirmed, name='payment-confirmed'),
    path('payment-unfinished/', user_views.payment_unfinished, name='payment-unfinished'),
    path('payment-error/', user_views.payment_error, name='payment-error'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    re_path(r'^robots\.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: ", mimetype="text/plain")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

resumes/urls.py
from django.urls import path

from . import views
from users import views as user_views

urlpatterns = [
    path('', views.my_resumes, name='my-resumes'),
    path('edit-profile/', views.edit_profile, name='edit-profile'),
    path('delete/<int:pk>/', views.delete_resume, name='delete-resume'),
    path('resume/create/', views.ResumeWizard.as_view(views.FORMS), name='create-resume'),
    path('edit/resume/<int:pk>/', views.ResumeWizard.as_view(views.FORMS), name='edit-resume'),
    path('faq/', views.faq, name='faq'),
    path('templates/', views.templates, name='templates'),
    path('payment/', user_views.payment, name='payment'),
    path('payment/notification/', user_views.payment_notification, name='payment-notif'),
    path('resume/<int:pk>/choose/', views.choose, name='choose'),
    path('resume/<int:pk>/view-resume/', views.choose, name='view-resume'),
]

resumes/models.py
from django.db import models

from .choices import LANGUAGE_COMPETENCY_CHOICES, SKILL_COMPETENCY_CHOICES
from users.models import User

from tinymce.models import HTMLField


class Resume(models.Model):
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)

    def __str__(self):
        return self.name


class WorkExperience(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, blank=True)
    position = models.CharField(max_length=255, blank=True)
    company = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=255, blank=True)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    achievements = HTMLField(blank=True)

    def __str__(self):
        return self.position

    class Meta:
        verbose_name_plural = "Work Experience"
        ordering = ['-end_date', ]


class Certification(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, blank=True)
    name = models.CharField(max_length=255, blank=True)
    date_obtained = models.DateField(null=True, blank=True)
    city = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-date_obtained', ]


class Education(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, blank=True)
    school = models.CharField(max_length=255, blank=True)
    degree = models.CharField(max_length=255, blank=True)
    major = models.CharField(max_length=255, blank=True)
    gpa = models.FloatField(null=True, blank=True)
    city = models.CharField(max_length=255, blank=True)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.school

    class Meta:
        verbose_name_plural = "Education"
        ordering = ['-end_date', ]


class Skill(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, blank=True)
    name = models.CharField(max_length=255, blank=True)
    competency = models.IntegerField(choices=SKILL_COMPETENCY_CHOICES, null=True, blank=True)

    def __str__(self):
        return self.name


class Language(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE, blank=True)
    name = models.CharField(max_length=255, blank=True)
    competency = models.IntegerField(choices=LANGUAGE_COMPETENCY_CHOICES, null=True, blank=True)

    def __str__(self):
        return self.name

resumes/views.py
import logging

from django.contrib.auth.models import Group
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.urls import reverse
from formtools.wizard.views import SessionWizardView

from users.forms import CustomUserChangeForm
from .forms import (ResumeForm, ProfileUpdateForm, WorkExperienceFormSet, CertificationFormSet,
                    EducationFormSet, SkillFormSet, LanguageFormSet)
from .models import Resume, WorkExperience, Certification, Education, Skill, Language
from .forms import ChooseForm

import pdfcrowd

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

FORMS = [('resumes', ResumeForm),
         ('work_experience', WorkExperienceFormSet),
         ('certifications', CertificationFormSet),
         ('education', EducationFormSet),
         ('skills', SkillFormSet),
         ('languages', LanguageFormSet), ]

FORM_TYPES = ('work_experience', 'certifications', 'education', 'skills', 'languages')

TEMPLATES = {'resumes': 'resumes/resumes.html',
             'work_experience': 'resumes/work_experience.html',
             'certifications': 'resumes/certifications.html',
             'education': 'resumes/education.html',
             'skills': 'resumes/skills.html',
             'languages': 'resumes/languages.html', }


@login_required()
def choose(request, pk):
    user = request.user
    pp_url = user.profile.profile_pic.url.strip('/')
    resume = Resume.objects.get(pk=pk)
    form = ChooseForm(request.POST)
    group = Group.objects.get(name='paying_user')
    if request.method == 'GET':
        form = ChooseForm()
    elif request.method == 'POST' and 'view-resume' in request.POST:
        if form.is_valid() and form.cleaned_data['resume_template'] == 'jakarta':
            return render(request, 'resumes/jakarta.html', {'form': form, 'resume': resume, 'pp_url': pp_url})
        if form.is_valid() and form.cleaned_data['resume_template'] == 'new_york':
            return render(request, 'resumes/new_york.html', {'form': form, 'resume': resume, 'pp_url': pp_url})
        if form.is_valid() and form.cleaned_data['resume_template'] == 'tokyo':
            return render(request, 'resumes/tokyo.html', {'form': form, 'resume': resume, 'pp_url': pp_url})
        if form.is_valid() and form.cleaned_data['resume_template'] == 'rome':
            return render(request, 'resumes/rome.html', {'form': form, 'resume': resume, 'pp_url': pp_url})
        if form.is_valid() and form.cleaned_data['resume_template'] == 'sf':
            return render(request, 'resumes/san_francisco.html', {'form': form, 'resume': resume, 'pp_url': pp_url})
    # two buttons on one page
    elif form.is_valid() and request.method == 'POST' and 'export-resume' in request.POST:
        if request.user.groups.filter(name='paying_user').exists():
            # code for exporting pdfcrowd goes here
            client = pdfcrowd.HtmlToPdfClient('chrisgunawan85', 'ea5734a7dc5aabbded5e65d8a32de8a4')
            client.setUsePrintMedia(True)
            client.setPageHeight('-1')
            client.setDebugLog(True)
            # set HTTP response headers
            pdf_response = HttpResponse(content_type='application/pdf')
            pdf_response['Cache-Control'] = 'max-age=0'
            pdf_response['Accept-Ranges'] = 'none'
            content_disp = 'attachment' if 'asAttachment' in request.POST else 'inline'
            pdf_response['Content-Disposition'] = content_disp + '; filename=my_resume.pdf'

            if form.cleaned_data['resume_template'] == 'jakarta':
                html = render_to_string('resumes/jakarta.html', {'resume': resume, 'pp_url': pp_url})
            if form.cleaned_data['resume_template'] == 'new_york':
                html = render_to_string('resumes/new_york.html', {'resume': resume, 'pp_url': pp_url})
            if form.cleaned_data['resume_template'] == 'tokyo':
                html = render_to_string('resumes/tokyo.html', {'resume': resume, 'pp_url': pp_url})
            if form.cleaned_data['resume_template'] == 'rome':
                html = render_to_string('resumes/rome.html', {'resume': resume, 'pp_url': pp_url})
            if form.cleaned_data['resume_template'] == 'sf':
                html = render_to_string('resumes/san_francisco.html', {'resume': resume, 'pp_url': pp_url})

            client.convertStringToStream(html, pdf_response)
            # send the generated PDF
            return pdf_response
        else:
            messages.info(request, "Please purchase a package to export to PDF format")
            return HttpResponseRedirect(reverse('resumes:payment'))
    return render(request, 'resumes/choose.html', {'form': form, 'resume': resume})


@login_required()
def my_resumes(request):
    user = request.user
    resumes = Resume.objects.filter(user=user).order_by('-created_at')
    return render(request, 'resumes/my_resumes.html', {'resumes': resumes})


@login_required()
def faq(request):
    return render(request, 'resumes/faq.html')


@login_required()
def templates(request):
    return render(request, 'resumes/templates.html')


@login_required()
def edit_profile(request):
    if request.method == 'POST':
        u_form = CustomUserChangeForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, 'Your profile has been saved!')
            return HttpResponseRedirect(reverse('resumes:edit-profile'))
    else:
        u_form = CustomUserChangeForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
    context = {'p_form': p_form,
               'u_form': u_form,
               }
    return render(request, 'resumes/profile.html', context)


@login_required()
def delete_resume(request, pk):
    resume = Resume.objects.get(pk=pk)
    resume.delete()
    messages.success(request, "Your resume has been deleted!")
    return HttpResponseRedirect(reverse('resumes:my-resumes'))


def dict_has_data(input_dict):
    has_data = False
    for key in input_dict:
        if input_dict[key]:
            has_data = True
            break
    return has_data


class ResumeWizard(LoginRequiredMixin, SessionWizardView):
    login_url = '/login/'

    def get_form_initial(self, step):
        if 'pk' in self.kwargs:
            return {}
        return self.initial_dict.get(step, {})

    def get_form_instance(self, step):
        if 'pk' in self.kwargs:
            pk = self.kwargs['pk']
            resume = Resume.objects.get(id=pk)

            if step == 'resumes':
                return resume

            if step == 'work_experience':
                return resume.workexperience_set.all()

            if step == 'certifications':
                return resume.certification_set.all()

            if step == 'education':
                return resume.education_set.all()

            if step == 'skills':
                return resume.skill_set.all()

            if step == 'languages':
                return resume.language_set.all()
        else:
            if step == 'resumes':
                return None

            if step == 'work_experience':
                return WorkExperience.objects.none()

            if step == 'certifications':
                return Certification.objects.none()

            if step == 'education':
                return Education.objects.none()

            if step == 'skills':
                return Skill.objects.none()

            if step == 'languages':
                return Language.objects.none()
        return None

    def get_template_names(self):
        return [TEMPLATES[self.steps.current]]

    def done(self, form_list, **kwargs):
        user = self.request.user
        resume_form_data = self.get_cleaned_data_for_step('resumes')
        resume_name = resume_form_data['name']
        if 'pk' in self.kwargs:
            pk = self.kwargs['pk']
        else:
            pk = None
        resume, created = Resume.objects.update_or_create(id=pk, defaults={'user': user,
                                                                           'name': resume_name, })

        for form_name in FORM_TYPES:
            form_data_list = self.get_cleaned_data_for_step(form_name)
            for form_data in form_data_list:
                if not dict_has_data(form_data):
                    continue
                form_data['resume'] = resume

                form_instance = self.get_form(step=form_name)
                obj = form_data.pop('id')
                if obj:
                    form_instance.model.objects.filter(id=obj.id).update(**form_data)
                else:
                    form_instance.model.objects.create(**form_data)

        messages.add_message(self.request, messages.SUCCESS, 'Your resume has been saved!')
        return HttpResponseRedirect(reverse('resumes:my-resumes'))

resumes/templates/resumes/certifications.html
{% extends 'resumes/layout.html' %}
{% load i18n %}
{% load static %}
{% block title %}<title>EZResume | Certifications</title>{% endblock %}
{% block subheader %}
    <form action="" method="POST">{% csrf_token %}
        {{ wizard.management_form }}
        <div class="sub-header">
            <ul>
                <li><button name="wizard_goto_step" type="submit" value="resumes">1. Resume Info</button></li>
                <li><button name="wizard_goto_step" type="submit" value="work_experience">2. Work Experience</button></li>
                <li><button name="wizard_goto_step" type="submit" value="certifications" class="active">3. Certifications</button></li>
                <li><button name="wizard_goto_step" type="submit" value="education">4. Education</button></li>
                <li><button name="wizard_goto_step" type="submit" value="skills">5. Skills</button></li>
                <li><button name="wizard_goto_step" type="submit" value="languages">6. Languages</button></li>
            </ul>
        </div>
    </form>
{% endblock %}

{% block content %}
    <form action="" class="form-labels-on-top" method="POST">{% csrf_token %}
    <p class="step-text">Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</p>
        <div class="form-title-row">
            <h1>Certifications</h1>
            <div class="tooltip">
                <i class="far fa-question-circle"></i>
                <span class="tool-tip-text">
                    If the position you are applying for requires fancy certifications, this is where you put them!
                    Maximum of 5 certification entries.
                </span>
            </div>
        </div>
        {{ wizard.management_form }}
        {% if wizard.form.forms %}
            {{ wizard.form.management_form }}
            {% for form in wizard.form.forms %}
                <div class="form-row form-duplicate">
                    {{ form.as_p }}
                </div>
            {% endfor %}
        {% else %}
            {% for form in formset %}
                <div class="form-row">
                    {{ form.as_p }}
                </div>
            {% endfor %}
        {% endif %}
    <div class="form-row">
        {% if wizard.steps.prev %}
            <button name="wizard_goto_step" class="button-previous" type="submit" value="{{ wizard.steps.prev }}">{% trans "Previous" %}</button>
        {% endif %}
        <button type="submit" class="button-next">Next</button>
    </div>
    </form>
{% endblock %}
{% block script %}
    <script type="text/javascript">
        $(function() {
            $('.form-duplicate').formset({ prefix: 'certifications' });
        })
    </script>
{% endblock %}

resumes/templates/resumes/choose.html
{% extends 'resumes/layout.html' %}
{% load static %}
{% block style %}
    <style>

    input[type=radio] {
        display: none;
    }

    input#id_resume_template_0[type=radio]+label {
        background-image: url("{% static 'resumes/images/jakarta-resume-small.jpg' %}");
        border: lightslategray solid 1px;
        height: 253px;
        width: 223px;
        display: inline-block;
        margin: 1.5em;
    }

    input#id_resume_template_1[type=radio]+label {
        background-image: url("{% static 'resumes/images/new-york-resume-small.jpg' %}");
        border: lightslategray solid 1px;
        height: 253px;
        width: 223px;
        display: inline-block;
        margin: 1.5em;
    }

    input#id_resume_template_2[type=radio]+label {
        background-image: url("{% static 'resumes/images/tokyo-resume-small.jpg' %}");
        border: lightslategray solid 1px;
        height: 253px;
        width: 223px;
        display: inline-block;
        margin: 1.5em;
    }

    input#id_resume_template_3[type=radio]+label {
        background-image: url("{% static 'resumes/images/rome-resume-small.jpg' %}");
        border: lightslategray solid 1px;
        height: 253px;
        width: 223px;
        display: inline-block;
        margin: 1.5em;
    }

    input#id_resume_template_4[type=radio]+label {
        background-image: url("{% static 'resumes/images/sf-resume-small.jpg' %}");
        border: lightslategray solid 1px;
        height: 253px;
        width: 223px;
        display: inline-block;
        margin: 1.5em;
    }

    input#id_resume_template_0[type=radio]:checked+label {
        border: deeppink solid 4px;
        height: 253px;
        width: 223px;
        display: inline-block;
        margin: 1.5em;
    }

    input#id_resume_template_1[type=radio]:checked+label {
        border: deeppink solid 4px;
        height: 253px;
        width: 223px;
        display: inline-block;
        margin: 1.5em;
    }

    input#id_resume_template_2[type=radio]:checked+label {
        border: deeppink solid 4px;
        height: 253px;
        width: 223px;
        display: inline-block;
        margin: 1.5em;
    }

    input#id_resume_template_3[type=radio]:checked+label {
        border: deeppink solid 4px;
        height: 253px;
        width: 223px;
        display: inline-block;
        margin: 1.5em;
    }

    input#id_resume_template_4[type=radio]:checked+label {
        border: deeppink solid 4px;
        height: 253px;
        width: 223px;
        display: inline-block;
        margin: 1.5em;
    }

    </style>

{% endblock %}
{% block title %}<title>EZResume | Templates</title>{% endblock %}
{% block subheader %}
    <div class="sub-header">
        <h1>Choose Your Resume Template</h1>
    </div>
{% endblock %}
{% block content %}
    <div class="form-labels-on-top-small templates-page">
        <form method="post" action="{% url 'resumes:view-resume' pk=resume.id %}">
            {% csrf_token %}
            <input type="radio" name='resume_template' id="id_resume_template_0" value="jakarta" /><label for="id_resume_template_0"></label>
            <input type="radio" name='resume_template' id="id_resume_template_1" value="new_york" /><label for="id_resume_template_1"></label>
            <input type="radio" name='resume_template' id="id_resume_template_2" value="tokyo"/><label for="id_resume_template_2"></label>
            <input type="radio" name='resume_template' id="id_resume_template_3" value="rome" /><label for="id_resume_template_3"></label>
            <input type="radio" name='resume_template' id="id_resume_template_4" value="sf" /><label for="id_resume_template_4"></label>
            <div>
                {{ form.errors.resume_template }}
                <button type="submit" name="view-resume" class="button">View my resume</button>
                <button type="submit" name="export-resume" class="button">PDF my resume</button>
            </div>
        </form>
    </div>
{% endblock %}

resumes/templates/resumes/done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ form_data }}
</body>
</html>

resumes/templates/resumes/education.html
{% extends 'resumes/layout.html' %}
{% load i18n %}
{% load static %}
{% block title %}<title>EZResume | Education</title>{% endblock %}
{% block subheader %}
    <form action="" method="POST">{% csrf_token %}
        {{ wizard.management_form }}
        <div class="sub-header">
            <ul>
                <li><button name="wizard_goto_step" type="submit" value="resumes">1. Resume Info</button></li>
                <li><button name="wizard_goto_step" type="submit" value="work_experience">2. Work Experience</button></li>
                <li><button name="wizard_goto_step" type="submit" value="certifications">3. Certifications</button></li>
                <li><button name="wizard_goto_step" type="submit" value="education" class="active">4. Education</button></li>
                <li><button name="wizard_goto_step" type="submit" value="skills">5. Skills</button></li>
                <li><button name="wizard_goto_step" type="submit" value="languages">6. Languages</button></li>
            </ul>
        </div>
    </form>
{% endblock %}

{% block content %}
    <form action="" class="form-labels-on-top" method="POST">{% csrf_token %}
    <p class="step-text">Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</p>
        <div class="form-title-row">
            <h1>Education</h1>
            <div class="tooltip">
                <i class="far fa-question-circle"></i>
                <span class="tool-tip-text">
                    Only include higher education such as colleges, universities or institutes. It is not recommended
                    to include your high school information. Maximum is 3 education entries.
                </span>
            </div>
        </div>
        {{ wizard.management_form }}
        {% if wizard.form.forms %}
            {{ wizard.form.management_form }}
            {% for form in wizard.form.forms %}
                <div class="form-row form-duplicate">
                {{ form.as_p }}
                </div>
        {% endfor %}
        {% else %}
            <div class="form-row">
            {{ wizard.form.as_p }}
            </div>
        {% endif %}
    <div class="form-row">
        {% if wizard.steps.prev %}
            <button name="wizard_goto_step" class="button-previous" type="submit" value="{{ wizard.steps.prev }}">{% trans "Previous" %}</button>
        {% endif %}
        <button type="submit" class="button-next">Next</button>
    </div>
    </form>
{% endblock %}
{% block script %}
    <script type="text/javascript">
        $(function() {
            $('.form-duplicate').formset({ prefix: 'education' });
        })
    </script>
{% endblock %}

resumes/templates/resumes/layout.html
{% load static %}
<!DOCTYPE html>

<html>

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/ico" href="{% static 'resumes/images/favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'resumes/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'resumes/css/jquery-ui.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
          integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    {% block style %}{% endblock %}
	{% block title %}{% endblock %}
</head>
<body>
    {% if messages %}
        <div class="messages">
            <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }} message-text"{% endif %}>{{ message }}</li>
            {% endfor %}
            </ul>
        </div>
    {% endif %}

	<header>
        <div class="header">
            <a href="{% url 'resumes:my-resumes' %}"><img src="{% static 'resumes/images/logo.png' %}" class="logo"></a>
            <div class="header-left">
                <a href="{% url 'resumes:my-resumes' %}">My Resumes</a>
                <a href="{% url 'resumes:edit-profile' %}">Profile</a>
                <a href="{% url 'resumes:templates' %}">Templates</a>
            </div>
            <div class="header-right">
                <div class="dropdown">
                    <div class="dropbtn">
                        <span class="profile-pic-small">
                            <img src="{{ user.profile.profile_pic.url }}">
                        </span>
                        <span class="username">{{ user.username }}  </span><i class="fa fa-caret-down"></i>
                    </div>
                    <div class="dropdown-content">
                    <a href="{% url 'resumes:faq' %}">FAQ</a>
                    <a href="{% url 'resumes:payment' %}">Buy Package</a>
                    <a href="{% url 'logout' %}">Logout</a>
                </div>
                </div>
            </div>
        </div>
    </header>

    {% block subheader %}{% endblock %}

    <div class="main-content">
        {% block popup %}{% endblock %}
        {% block content %}{% endblock %}
    </div>
    <div class="footer">
        <img src="{% static 'resumes/images/logo-stack.png' %}" class="logo-footer">
        <p>Jakarta, Indonesia</p>
        <p>chrisgunawan@gmail.com</p>
    </div>
    <script src="{% static 'resumes/js/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'resumes/js/jquery-ui.js' %}"></script>
    <script src="{% static 'resumes/js/jquery.formset.js' %}"></script>
    <script src="{% static '/js/tinymce/tinymce.min.js' %}"></script>
    <script src="{% static 'resumes/js/scripts.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/tinymce/custom.js' %}"></script>
    <script type="text/javascript">
        // Initialize tinymce on page load
        $(document).ready(function() {
            tinymceInit();
        });
    </script>
    {% block script %}{% endblock %}
</body>
</html>

resumes/templates/resumes/my_resumes.html
{% extends 'resumes/layout.html' %}
{% load static %}
{% block title %}<title>EZResume | My Resumes</title>{% endblock %}
{% block content %}
    <div class="wrapper">
    {% for resume in resumes %}
       <div class="resume-box">
            <div class="container">
                <p class="resume-name">{{ resume.name }}</p>
                <p>Created on {{ resume.created_at }}</p>
                <div class="button-row">
                    <a href="{% url 'resumes:delete-resume' pk=resume.id %}" class="confirm-delete">Delete</a>
                    <a href="{% url 'resumes:edit-resume' pk=resume.id %}" class="edit-resume">Edit</a>
                    <a href="{% url 'resumes:choose' pk=resume.id %}" class="view-resume">View</a>
                </div>
            </div>
        </div>
    {% empty %}
        <div class="empty-state-box">
            <img src="{% static 'resumes/images/resume-empty-icon.png' %}" class="centered">
            <p class="empty-state-text"><b>You don't have any resumes yet</b><br>Create one and
                start building your very first resume</p>
        </div>
    {% endfor %}
        <div class="button-box">
            <a href="{% url 'resumes:create-resume' %}" class="button">Create a resume</a>
        </div>
    </div>
{% endblock %}